resilience4j:
  retry:
    instances:
      paymentService:
        max-attempts: 3
        wait-duration: 1s
  circuitbreaker:
    instances:
      paymentService:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

server:
  port: 8081
spring:
  application:
    name: hld-reliability-demo